### ISSUE TITLE
すべてのファイル先頭に法令名を

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-122#10]
https://github.com/law-of-japan/19590413-law-121/issues/5#issue-438172044

と同じです。本則、附則、READMEすべて一行目に見出し１で法令名を記述するようにしてください。

# 特許法施行法

のようにです。

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
