### ISSUE TITLE
ブランチ名について

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-122#2]
こちらも特許法と同じで、ブランチ名を
yyyymmdd_number
形式に
19540413_122
にしてもらえますか？

**Comment by Heat-Exchange** [comment]
変更しました。もう一度確認をお願いいたします。

**Comment by pinfort** [comment]
かしこまりました。お待ちください。

**Comment by pinfort** [comment]
ブランチ名の形式は大丈夫ですが、年が間違っているのでリポジトリ名と合わせて再修正が必要なようです

**Comment by Heat-Exchange** [comment]
ブランチ名・リポジトリ名を変更しました

**Comment by pinfort** [comment]
確認しました。
