### ISSUE TITLE
READMEに記述する「分類」について

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-122#5]
分類は、日本法令索引に記述されている分類を記述してください。
http://hourei.ndl.go.jp/SearchSys/viewEnkaku.do?i=3WuzlvXeautBqDR346QDiw%3D%3D
これによれば、この法律の分類は

- 産業一般
- 工業所有権
- 特許

です。

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
