### ISSUE TITLE
READMEにおける法令の英語名称の見出しについて

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-122#9]
現在、英語名称の見出しが

## 英語名称

になっていますが、既存のリポジトリでは

## 英訳名称

としています。基本的にこれに変えていただきたいと思います。但し、表記を英語名称とすることも検討しようと思います。

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
とりあえず英訳名称のままでいいことにしましょう。
